-- ── Event Sites Registry ──────────────────────────────────────────────────────
-- Tracks every site generated by TAOS for an event.
-- One record per event (upsert on event_id).
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists event_sites (
  id           uuid        primary key default gen_random_uuid(),
  event_id     uuid        not null references events(id) on delete cascade,
  template_id  text        not null,
  repo_name    text,
  repo_url     text,
  worker_name  text,
  site_url     text,
  status       text        not null default 'deploying',  -- deploying | live | error
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- One active deployment per event
create unique index if not exists event_sites_event_id_idx on event_sites (event_id);

-- RLS: super_admins read/write; others read-only
alter table event_sites enable row level security;

create policy "event_sites_read" on event_sites
  for select using (true);

create policy "event_sites_write" on event_sites
  for all using (
    exists (
      select 1 from staff_members
      where email = (select email from auth.users where id = auth.uid())
      and role in ('super_admin', 'admin')
    )
  );
