'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'

const C = {
  bg: '#E8EEF4', surface: '#FFFFFF', border: '#DDE8EE', text: '#0F1923', muted: '#5B7080',
  teal: '#00695C', green: '#C0F43C', purple: '#7C3AED', red: '#FF6B6B',
}

type Workspace = { id: string; name: string }

const FIELD_LABEL: React.CSSProperties = { fontSize: '13px', fontWeight: 700, color: C.muted, letterSpacing: '0.8px', textTransform: 'uppercase', display: 'block', marginBottom: '5px' }
const INPUT: React.CSSProperties = { width: '100%', padding: '9px 12px', borderRadius: '9px', border: `1px solid ${C.border}`, background: C.surface, color: C.text, fontSize: '13px', fontFamily: 'inherit', boxSizing: 'border-box' }

export default function ProposalCreatorPage() {
  const [form, setForm] = useState({
    client_name: '', client_type: 'government', country: '', city: '',
    event_concept_name: '', event_concept_description: '',
    trescon_role: 'full-management', target_scale: '', themes: '',
    government_agenda: '', competing_events: '', client_objectives: '', existing_relationship: '',
  })
  const [showOptional, setShowOptional] = useState(false)
  const [workspaces, setWorkspaces] = useState<Workspace[]>([])
  const [workspaceId, setWorkspaceId] = useState('')

  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState('')
  const [proposal, setProposal] = useState('')
  const [title, setTitle] = useState('')
  const [copied, setCopied] = useState(false)
  const [saving, setSaving] = useState(false)
  const [saveMsg, setSaveMsg] = useState('')

  useEffect(() => {
    fetch('/api/bd-workspaces').then(r => r.json()).then(d => setWorkspaces(Array.isArray(d) ? d : [])).catch(() => {})
  }, [])

  function set<K extends keyof typeof form>(key: K, value: string) {
    setForm(p => ({ ...p, [key]: value }))
  }

  async function generate() {
    if (!form.client_name.trim() || !form.event_concept_name.trim()) {
      setError('Client name and event concept name are required.'); return
    }
    setGenerating(true); setError(''); setSaveMsg('')
    try {
      const res  = await fetch('/api/kb/generators/proposal-creator', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form),
      })
      const data = await res.json()
      if (!res.ok) { setError(data.error ?? 'Generation failed. Please try again.'); setGenerating(false); return }
      setProposal(data.proposal)
      setTitle(data.title)
    } catch {
      setError('Could not reach the server. Check your connection and try again.')
    }
    setGenerating(false)
  }

  async function copyToClipboard() {
    await navigator.clipboard.writeText(proposal)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  async function saveToKB() {
    setSaving(true); setSaveMsg('')
    const submittedBy = sessionStorage.getItem('tai_admin_staff_id')
    const res = await fetch('/api/kb/save-generated', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title, type: 'proposal', content: proposal,
        layer: 'specific', department: 'events', min_level: 'team_lead', pilot_use: false,
        workspace_id: workspaceId || undefined,
        submitted_by: submittedBy || undefined,
        ai_reasoning: `Generated by Proposal Creator for ${form.client_name} — ${form.event_concept_name}. Awaiting admin publish.`,
      }),
    })
    if (res.ok) setSaveMsg('Saved to Knowledge Base — pending review in the admin Knowledge tab.')
    else setSaveMsg('Could not save. Please try again.')
    setSaving(false)
  }

  return (
    <div style={{ minHeight: '100vh', background: C.bg, fontFamily: 'var(--font-manrope), Manrope, sans-serif' }}>
      <div style={{ background: C.surface, borderBottom: `1px solid ${C.border}`, padding: '0 32px', height: '58px', display: 'flex', alignItems: 'center', gap: '12px' }}>
        <Link href="/admin?tab=knowledge&sub=workspaces" style={{ textDecoration: 'none' }}>
          <img src="/trescon-logo.png" alt="Trescon" style={{ height: '34px', width: 'auto' }} />
        </Link>
        <div style={{ width: '1px', height: '20px', background: C.border }} />
        <div style={{ fontSize: '13px', fontWeight: 800, color: C.text }}>Proposal Creator</div>
        <Link href="/admin?tab=knowledge&sub=workspaces" style={{ marginLeft: 'auto', fontSize: '13px', fontWeight: 700, color: C.muted, textDecoration: 'none' }}>‹ Knowledge Base</Link>
      </div>

      <div style={{ maxWidth: '860px', margin: '0 auto', padding: '40px 24px 80px', display: 'grid', gap: '24px' }}>
        <div>
          <div style={{ fontSize: '13px', fontWeight: 800, letterSpacing: '2.5px', textTransform: 'uppercase', color: C.purple, marginBottom: '8px' }}>Knowledge Base — Generator</div>
          <h1 style={{ fontSize: '32px', fontWeight: 900, margin: '0 0 8px', letterSpacing: '-0.4px', color: C.text }}>Proposal Creator</h1>
          <p style={{ fontSize: '13px', color: C.muted, margin: 0, lineHeight: 1.6 }}>
            Describe the prospect and event concept. Trescon&rsquo;s credentials, commercial models, and the most relevant historical proposals and event reports are pulled in automatically.
          </p>
        </div>

        {/* Step 1 — Input */}
        <div style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: '16px', padding: '24px' }}>
          <div style={{ fontSize: '13px', fontWeight: 800, color: C.text, marginBottom: '16px' }}>1. Prospect &amp; Event Concept</div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '12px' }}>
            <div>
              <label style={FIELD_LABEL}>Client / Prospect Name</label>
              <input value={form.client_name} onChange={e => set('client_name', e.target.value)} placeholder="e.g. Dubai Land Department" style={INPUT} />
            </div>
            <div>
              <label style={FIELD_LABEL}>Client Type</label>
              <select value={form.client_type} onChange={e => set('client_type', e.target.value)} style={INPUT}>
                <option value="government">Government Body</option>
                <option value="private">Private Enterprise</option>
                <option value="ngo">NGO</option>
                <option value="other">Other</option>
              </select>
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '12px' }}>
            <div>
              <label style={FIELD_LABEL}>Country</label>
              <input value={form.country} onChange={e => set('country', e.target.value)} placeholder="e.g. UAE" style={INPUT} />
            </div>
            <div>
              <label style={FIELD_LABEL}>City</label>
              <input value={form.city} onChange={e => set('city', e.target.value)} placeholder="e.g. Dubai" style={INPUT} />
            </div>
          </div>

          <div style={{ marginBottom: '12px' }}>
            <label style={FIELD_LABEL}>Proposed Event Concept — Name</label>
            <input value={form.event_concept_name} onChange={e => set('event_concept_name', e.target.value)} placeholder="e.g. LivingSphere Summit" style={INPUT} />
          </div>

          <div style={{ marginBottom: '12px' }}>
            <label style={FIELD_LABEL}>One-line Description</label>
            <input value={form.event_concept_description} onChange={e => set('event_concept_description', e.target.value)} placeholder="What is this event, in one sentence?" style={INPUT} />
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '12px' }}>
            <div>
              <label style={FIELD_LABEL}>Trescon&rsquo;s Proposed Role</label>
              <select value={form.trescon_role} onChange={e => set('trescon_role', e.target.value)} style={INPUT}>
                <option value="full-management">Full Management</option>
                <option value="content">Content Only</option>
                <option value="commercial">Commercial Only</option>
                <option value="advisory">Advisory</option>
              </select>
            </div>
            <div>
              <label style={FIELD_LABEL}>Target Scale</label>
              <input value={form.target_scale} onChange={e => set('target_scale', e.target.value)} placeholder="e.g. 3,000 attendees, AED 3M budget" style={INPUT} />
            </div>
          </div>

          <div style={{ marginBottom: '4px' }}>
            <label style={FIELD_LABEL}>Key Themes / Sectors</label>
            <input value={form.themes} onChange={e => set('themes', e.target.value)} placeholder="e.g. AI regulation, smart cities, sustainability" style={INPUT} />
          </div>

          <details style={{ marginTop: '16px' }} open={showOptional} onToggle={e => setShowOptional((e.target as HTMLDetailsElement).open)}>
            <summary style={{ fontSize: '13px', fontWeight: 700, color: C.muted, cursor: 'pointer', userSelect: 'none' }}>Optional details (improves output quality)</summary>
            <div style={{ marginTop: '12px', display: 'grid', gap: '12px' }}>
              <div>
                <label style={FIELD_LABEL}>Government Agenda / National Strategy Alignment</label>
                <input value={form.government_agenda} onChange={e => set('government_agenda', e.target.value)} placeholder="e.g. Dubai D33, Saudi Vision 2030" style={INPUT} />
              </div>
              <div>
                <label style={FIELD_LABEL}>Competing Events in the Market</label>
                <input value={form.competing_events} onChange={e => set('competing_events', e.target.value)} style={INPUT} />
              </div>
              <div>
                <label style={FIELD_LABEL}>Client&rsquo;s Stated Objectives / Pain Points</label>
                <input value={form.client_objectives} onChange={e => set('client_objectives', e.target.value)} style={INPUT} />
              </div>
              <div>
                <label style={FIELD_LABEL}>Existing Relationship / Prior Conversations</label>
                <input value={form.existing_relationship} onChange={e => set('existing_relationship', e.target.value)} style={INPUT} />
              </div>
            </div>
          </details>

          {error && <div style={{ marginTop: '14px', fontSize: '13px', padding: '9px 12px', borderRadius: '8px', background: 'rgba(255,107,107,0.07)', border: '1px solid rgba(255,107,107,0.2)', color: C.red }}>{error}</div>}

          <button onClick={generate} disabled={generating}
            style={{ marginTop: '18px', width: '100%', padding: '12px', borderRadius: '9px', border: 'none', background: generating ? C.border : C.purple, color: '#FFFFFF', fontSize: '13px', fontWeight: 800, cursor: generating ? 'not-allowed' : 'pointer', fontFamily: 'inherit' }}>
            {generating ? 'Generating proposal… this can take a minute' : proposal ? 'Regenerate Proposal' : 'Generate Proposal'}
          </button>
        </div>

        {/* Step 2 — Review */}
        {proposal && (
          <div style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: '16px', padding: '24px' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '14px', flexWrap: 'wrap', gap: '10px' }}>
              <div style={{ fontSize: '13px', fontWeight: 800, color: C.text }}>2. Review &amp; Edit</div>
              <button onClick={copyToClipboard}
                style={{ fontSize: '13px', fontWeight: 700, color: C.teal, background: 'none', border: `1px solid ${C.teal}40`, borderRadius: '8px', padding: '6px 14px', cursor: 'pointer', fontFamily: 'inherit' }}>
                {copied ? 'Copied!' : 'Copy to Clipboard'}
              </button>
            </div>

            <textarea value={proposal} onChange={e => setProposal(e.target.value)}
              style={{ width: '100%', minHeight: '480px', padding: '16px', borderRadius: '10px', border: `1px solid ${C.border}`, background: C.bg, color: C.text, fontSize: '13px', fontFamily: 'ui-monospace, monospace', lineHeight: 1.6, boxSizing: 'border-box', resize: 'vertical' }} />

            <div style={{ marginTop: '16px', paddingTop: '16px', borderTop: `1px solid ${C.border}` }}>
              <label style={FIELD_LABEL}>Link to BD Workspace <span style={{ textTransform: 'none', fontWeight: 500 }}>(optional)</span></label>
              <select value={workspaceId} onChange={e => setWorkspaceId(e.target.value)} style={{ ...INPUT, marginBottom: '12px' }}>
                <option value="">Not linked to a workspace</option>
                {workspaces.map(ws => <option key={ws.id} value={ws.id}>{ws.name}</option>)}
              </select>

              {saveMsg && <div style={{ marginBottom: '10px', fontSize: '13px', padding: '9px 12px', borderRadius: '8px', background: saveMsg.includes('Saved') ? 'rgba(192,244,60,0.08)' : 'rgba(255,107,107,0.07)', border: `1px solid ${saveMsg.includes('Saved') ? 'rgba(192,244,60,0.25)' : 'rgba(255,107,107,0.2)'}`, color: saveMsg.includes('Saved') ? '#3D6B00' : C.red }}>{saveMsg}</div>}

              <button onClick={saveToKB} disabled={saving}
                style={{ width: '100%', padding: '11px', borderRadius: '9px', border: 'none', background: saving ? C.border : C.green, color: C.text, fontSize: '13px', fontWeight: 800, cursor: saving ? 'not-allowed' : 'pointer', fontFamily: 'inherit' }}>
                {saving ? 'Saving…' : 'Save to Knowledge Base'}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
