'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'

const C = {
  bg: '#E8EEF4', surface: '#FFFFFF', border: '#DDE8EE', text: '#0F1923', muted: '#5B7080',
  teal: '#00695C', green: '#C0F43C', blue: '#60A5FA', red: '#FF6B6B',
}

type Workspace = { id: string; name: string }

const FIELD_LABEL: React.CSSProperties = { fontSize: '13px', fontWeight: 700, color: C.muted, letterSpacing: '0.8px', textTransform: 'uppercase', display: 'block', marginBottom: '5px' }
const INPUT: React.CSSProperties = { width: '100%', padding: '9px 12px', borderRadius: '9px', border: `1px solid ${C.border}`, background: C.surface, color: C.text, fontSize: '13px', fontFamily: 'inherit', boxSizing: 'border-box' }
const TEXTAREA: React.CSSProperties = { ...INPUT, minHeight: '72px', resize: 'vertical' as const }

const initialForm = {
  event_name: '', edition_year: '', date_start: '', date_end: '', venue: '', city: '', country: '',
  organiser: '', patronage: '',
  total_attendees: '', countries_count: '', speakers_count: '', exhibitors_count: '', sessions_count: '', mous: '',
  themes: '', sponsors_by_tier: '', media_stats: '', startup_competition: '',
  testimonials: '', key_outcomes: '',
  attendee_profile: '', session_titles: '', speaker_list: '', social_stats: '', yoy_comparison: '',
}

export default function PerCreatorPage() {
  const [form, setForm] = useState(initialForm)
  const [showOptional, setShowOptional] = useState(false)
  const [workspaces, setWorkspaces] = useState<Workspace[]>([])
  const [workspaceId, setWorkspaceId] = useState('')

  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState('')
  const [report, setReport] = useState('')
  const [title, setTitle] = useState('')
  const [copied, setCopied] = useState(false)
  const [saving, setSaving] = useState(false)
  const [saveMsg, setSaveMsg] = useState('')

  useEffect(() => {
    fetch('/api/bd-workspaces').then(r => r.json()).then(d => setWorkspaces(Array.isArray(d) ? d : [])).catch(() => {})
  }, [])

  function set<K extends keyof typeof form>(key: K, value: string) {
    setForm(p => ({ ...p, [key]: value }))
  }

  async function generate() {
    if (!form.event_name.trim() || !form.total_attendees.trim()) {
      setError('Event name and total attendees are required.'); return
    }
    setGenerating(true); setError(''); setSaveMsg('')
    try {
      const res  = await fetch('/api/kb/generators/per-creator', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form),
      })
      const data = await res.json()
      if (!res.ok) { setError(data.error ?? 'Generation failed. Please try again.'); setGenerating(false); return }
      setReport(data.report)
      setTitle(data.title)
    } catch {
      setError('Could not reach the server. Check your connection and try again.')
    }
    setGenerating(false)
  }

  async function copyToClipboard() {
    await navigator.clipboard.writeText(report)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  async function saveToKB() {
    setSaving(true); setSaveMsg('')
    const submittedBy = sessionStorage.getItem('tai_admin_staff_id')
    const res = await fetch('/api/kb/save-generated', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title, type: 'event_report', content: report,
        layer: 'knowledge_base', department: 'all', min_level: 'all', pilot_use: true,
        workspace_id: workspaceId || undefined,
        submitted_by: submittedBy || undefined,
        ai_reasoning: `Generated by PER Creator for ${form.event_name}. Awaiting admin publish.`,
      }),
    })
    if (res.ok) setSaveMsg('Saved to Knowledge Base — pending review in the admin Knowledge tab.')
    else setSaveMsg('Could not save. Please try again.')
    setSaving(false)
  }

  return (
    <div style={{ minHeight: '100vh', background: C.bg, fontFamily: 'var(--font-manrope), Manrope, sans-serif' }}>
      <div style={{ background: C.surface, borderBottom: `1px solid ${C.border}`, padding: '0 32px', height: '58px', display: 'flex', alignItems: 'center', gap: '12px' }}>
        <Link href="/admin?tab=knowledge&sub=documents" style={{ textDecoration: 'none' }}>
          <img src="/trescon-logo.png" alt="Trescon" style={{ height: '34px', width: 'auto' }} />
        </Link>
        <div style={{ width: '1px', height: '20px', background: C.border }} />
        <div style={{ fontSize: '13px', fontWeight: 800, color: C.text }}>PER Creator</div>
        <Link href="/admin?tab=knowledge&sub=documents" style={{ marginLeft: 'auto', fontSize: '13px', fontWeight: 700, color: C.muted, textDecoration: 'none' }}>‹ Knowledge Base</Link>
      </div>

      <div style={{ maxWidth: '860px', margin: '0 auto', padding: '40px 24px 80px', display: 'grid', gap: '24px' }}>
        <div>
          <div style={{ fontSize: '13px', fontWeight: 800, letterSpacing: '2.5px', textTransform: 'uppercase', color: C.blue, marginBottom: '8px' }}>Knowledge Base — Generator</div>
          <h1 style={{ fontSize: '32px', fontWeight: 900, margin: '0 0 8px', letterSpacing: '-0.4px', color: C.text }}>Post-Event Report Creator</h1>
          <p style={{ fontSize: '13px', color: C.muted, margin: 0, lineHeight: 1.6 }}>
            Enter the event data once it&rsquo;s wrapped. The most relevant past editions and Trescon&rsquo;s credentials are pulled in automatically for structure and the closing &ldquo;About Trescon&rdquo; section.
          </p>
        </div>

        {/* Step 1 — Input */}
        <div style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: '16px', padding: '24px' }}>
          <div style={{ fontSize: '13px', fontWeight: 800, color: C.text, marginBottom: '16px' }}>1. Event Data</div>

          <div style={{ fontSize: '13px', fontWeight: 800, color: C.muted, marginBottom: '10px' }}>Event Basics</div>
          <div style={{ marginBottom: '12px' }}>
            <label style={FIELD_LABEL}>Event Name</label>
            <input value={form.event_name} onChange={e => set('event_name', e.target.value)} placeholder="e.g. Dubai FinTech Summit" style={INPUT} />
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', marginBottom: '12px' }}>
            <div><label style={FIELD_LABEL}>Edition Year</label><input value={form.edition_year} onChange={e => set('edition_year', e.target.value)} placeholder="2026" style={INPUT} /></div>
            <div><label style={FIELD_LABEL}>Start Date</label><input value={form.date_start} onChange={e => set('date_start', e.target.value)} placeholder="YYYY-MM-DD" style={INPUT} /></div>
            <div><label style={FIELD_LABEL}>End Date</label><input value={form.date_end} onChange={e => set('date_end', e.target.value)} placeholder="YYYY-MM-DD" style={INPUT} /></div>
            <div><label style={FIELD_LABEL}>Venue</label><input value={form.venue} onChange={e => set('venue', e.target.value)} style={INPUT} /></div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', marginBottom: '12px' }}>
            <div><label style={FIELD_LABEL}>City</label><input value={form.city} onChange={e => set('city', e.target.value)} style={INPUT} /></div>
            <div><label style={FIELD_LABEL}>Country</label><input value={form.country} onChange={e => set('country', e.target.value)} style={INPUT} /></div>
            <div><label style={FIELD_LABEL}>Organiser</label><input value={form.organiser} onChange={e => set('organiser', e.target.value)} style={INPUT} /></div>
            <div><label style={FIELD_LABEL}>Patronage</label><input value={form.patronage} onChange={e => set('patronage', e.target.value)} style={INPUT} /></div>
          </div>

          <div style={{ fontSize: '13px', fontWeight: 800, color: C.muted, margin: '18px 0 10px' }}>Scale</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px', marginBottom: '12px' }}>
            <div><label style={FIELD_LABEL}>Total Attendees</label><input value={form.total_attendees} onChange={e => set('total_attendees', e.target.value)} placeholder="e.g. 9,000+" style={INPUT} /></div>
            <div><label style={FIELD_LABEL}>Countries Represented</label><input value={form.countries_count} onChange={e => set('countries_count', e.target.value)} style={INPUT} /></div>
            <div><label style={FIELD_LABEL}>Speakers</label><input value={form.speakers_count} onChange={e => set('speakers_count', e.target.value)} style={INPUT} /></div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px', marginBottom: '4px' }}>
            <div><label style={FIELD_LABEL}>Exhibitors / Sponsors</label><input value={form.exhibitors_count} onChange={e => set('exhibitors_count', e.target.value)} style={INPUT} /></div>
            <div><label style={FIELD_LABEL}>Sessions / Stages</label><input value={form.sessions_count} onChange={e => set('sessions_count', e.target.value)} style={INPUT} /></div>
            <div><label style={FIELD_LABEL}>MoUs Signed</label><input value={form.mous} onChange={e => set('mous', e.target.value)} style={INPUT} /></div>
          </div>

          <div style={{ fontSize: '13px', fontWeight: 800, color: C.muted, margin: '18px 0 10px' }}>Content &amp; Outcomes</div>
          <div style={{ display: 'grid', gap: '12px', marginBottom: '4px' }}>
            <div><label style={FIELD_LABEL}>Main Themes (one per line)</label><textarea value={form.themes} onChange={e => set('themes', e.target.value)} style={TEXTAREA} /></div>
            <div><label style={FIELD_LABEL}>Sponsors by Tier</label><textarea value={form.sponsors_by_tier} onChange={e => set('sponsors_by_tier', e.target.value)} placeholder="Headline: ...&#10;Gold: ...&#10;Silver: ..." style={TEXTAREA} /></div>
            <div><label style={FIELD_LABEL}>Media &amp; PR Stats</label><textarea value={form.media_stats} onChange={e => set('media_stats', e.target.value)} placeholder="PR value, impressions, articles, TV/radio…" style={TEXTAREA} /></div>
            <div><label style={FIELD_LABEL}>Startup Competition Outcomes</label><textarea value={form.startup_competition} onChange={e => set('startup_competition', e.target.value)} style={TEXTAREA} /></div>
            <div><label style={FIELD_LABEL}>Testimonials (attributed — quote, name, title, company per line)</label><textarea value={form.testimonials} onChange={e => set('testimonials', e.target.value)} style={TEXTAREA} /></div>
            <div><label style={FIELD_LABEL}>Key Outcomes Achieved</label><textarea value={form.key_outcomes} onChange={e => set('key_outcomes', e.target.value)} style={TEXTAREA} /></div>
          </div>

          <details style={{ marginTop: '16px' }} open={showOptional} onToggle={e => setShowOptional((e.target as HTMLDetailsElement).open)}>
            <summary style={{ fontSize: '13px', fontWeight: 700, color: C.muted, cursor: 'pointer', userSelect: 'none' }}>Optional details (improves output quality)</summary>
            <div style={{ marginTop: '12px', display: 'grid', gap: '12px' }}>
              <div><label style={FIELD_LABEL}>Attendee Profile Breakdown</label><textarea value={form.attendee_profile} onChange={e => set('attendee_profile', e.target.value)} placeholder="Seniority, sectors, geography…" style={TEXTAREA} /></div>
              <div><label style={FIELD_LABEL}>Session Titles</label><textarea value={form.session_titles} onChange={e => set('session_titles', e.target.value)} style={TEXTAREA} /></div>
              <div><label style={FIELD_LABEL}>Speaker List</label><textarea value={form.speaker_list} onChange={e => set('speaker_list', e.target.value)} placeholder="Name, title, organisation per line" style={TEXTAREA} /></div>
              <div><label style={FIELD_LABEL}>Social Media Stats</label><textarea value={form.social_stats} onChange={e => set('social_stats', e.target.value)} style={TEXTAREA} /></div>
              <div><label style={FIELD_LABEL}>Year-on-Year Comparison</label><textarea value={form.yoy_comparison} onChange={e => set('yoy_comparison', e.target.value)} style={TEXTAREA} /></div>
            </div>
          </details>

          {error && <div style={{ marginTop: '14px', fontSize: '13px', padding: '9px 12px', borderRadius: '8px', background: 'rgba(255,107,107,0.07)', border: '1px solid rgba(255,107,107,0.2)', color: C.red }}>{error}</div>}

          <button onClick={generate} disabled={generating}
            style={{ marginTop: '18px', width: '100%', padding: '12px', borderRadius: '9px', border: 'none', background: generating ? C.border : C.blue, color: '#0F1923', fontSize: '13px', fontWeight: 800, cursor: generating ? 'not-allowed' : 'pointer', fontFamily: 'inherit' }}>
            {generating ? 'Generating report… this can take a minute' : report ? 'Regenerate Report' : 'Generate Report'}
          </button>
        </div>

        {/* Step 2 — Review */}
        {report && (
          <div style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: '16px', padding: '24px' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '14px', flexWrap: 'wrap', gap: '10px' }}>
              <div style={{ fontSize: '13px', fontWeight: 800, color: C.text }}>2. Review &amp; Edit</div>
              <button onClick={copyToClipboard}
                style={{ fontSize: '13px', fontWeight: 700, color: C.teal, background: 'none', border: `1px solid ${C.teal}40`, borderRadius: '8px', padding: '6px 14px', cursor: 'pointer', fontFamily: 'inherit' }}>
                {copied ? 'Copied!' : 'Copy to Clipboard'}
              </button>
            </div>

            <textarea value={report} onChange={e => setReport(e.target.value)}
              style={{ width: '100%', minHeight: '480px', padding: '16px', borderRadius: '10px', border: `1px solid ${C.border}`, background: C.bg, color: C.text, fontSize: '13px', fontFamily: 'ui-monospace, monospace', lineHeight: 1.6, boxSizing: 'border-box', resize: 'vertical' }} />

            <div style={{ marginTop: '16px', paddingTop: '16px', borderTop: `1px solid ${C.border}` }}>
              <label style={FIELD_LABEL}>Link to BD Workspace <span style={{ textTransform: 'none', fontWeight: 500 }}>(optional)</span></label>
              <select value={workspaceId} onChange={e => setWorkspaceId(e.target.value)} style={{ ...INPUT, marginBottom: '12px' }}>
                <option value="">Not linked to a workspace</option>
                {workspaces.map(ws => <option key={ws.id} value={ws.id}>{ws.name}</option>)}
              </select>

              {saveMsg && <div style={{ marginBottom: '10px', fontSize: '13px', padding: '9px 12px', borderRadius: '8px', background: saveMsg.includes('Saved') ? 'rgba(192,244,60,0.08)' : 'rgba(255,107,107,0.07)', border: `1px solid ${saveMsg.includes('Saved') ? 'rgba(192,244,60,0.25)' : 'rgba(255,107,107,0.2)'}`, color: saveMsg.includes('Saved') ? '#3D6B00' : C.red }}>{saveMsg}</div>}

              <button onClick={saveToKB} disabled={saving}
                style={{ width: '100%', padding: '11px', borderRadius: '9px', border: 'none', background: saving ? C.border : C.green, color: C.text, fontSize: '13px', fontWeight: 800, cursor: saving ? 'not-allowed' : 'pointer', fontFamily: 'inherit' }}>
                {saving ? 'Saving…' : 'Save to Knowledge Base'}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
