import { supabaseAdmin } from '@/app/lib/supabase'
import { NextRequest, NextResponse } from 'next/server'

const ADMIN_CODE = process.env.NEXT_PUBLIC_ADMIN_CODE ?? 'taos2026'

const ADDITIONAL_COURSES = [
  /* ─── FOUNDATION 3 ─────────────────────────────────────────── */
  {
    title: 'AI Tools Overview: The Landscape in 2026',
    subtitle: 'Know what exists, what it does, and what to use when',
    tool_name: null,
    tier_level: 'foundation',
    dept_tags: [],
    is_mandatory: true,
    overview: `There are now hundreds of AI tools. Most people use one (ChatGPT) and ignore the rest. That's a gap in your toolkit.\n\nThis course maps the AI landscape clearly — what categories of tools exist, what each is built for, and how to pick the right one for any task. By the end, you'll have a personal AI toolkit with at least 3 tools you'll use regularly.`,
    read_content: `# The AI Tool Landscape — Clear Map\n\nAI tools fall into five categories. Each does something different.\n\n## 1. Text & Language AI\n**Tools:** ChatGPT, Claude, Gemini, Perplexity\n**Best for:** Writing, summarising, answering questions, brainstorming, coding\n**Pick:** ChatGPT or Claude for most tasks. Perplexity for research with citations.\n\n## 2. Image & Design AI\n**Tools:** Midjourney, Adobe Firefly, Canva AI, DALL-E\n**Best for:** Creating visuals, editing photos, concept design, social graphics\n**Pick:** Canva AI if you already use Canva. Midjourney for high-quality generation.\n\n## 3. Video & Audio AI\n**Tools:** Runway, HeyGen, ElevenLabs, Descript\n**Best for:** Video editing, AI avatars, voice cloning, podcast editing\n**Pick:** Descript for audio editing. HeyGen for AI-presented videos.\n\n## 4. Productivity & Workflow AI\n**Tools:** Notion AI, Zapier AI, Make, n8n, Microsoft Copilot\n**Best for:** Note-taking, task management, automating repetitive processes\n**Pick:** Notion AI if you use Notion. Zapier AI for connecting apps.\n\n## 5. Research & Intelligence AI\n**Tools:** Perplexity, Consensus, Elicit, LinkedIn AI\n**Best for:** Finding credible sources, market research, academic synthesis\n**Pick:** Perplexity for fast research. Consensus for evidence-based answers.\n\n## How to Choose\nAsk three questions:\n1. Is this a writing/thinking task? → Text AI\n2. Is this a visual task? → Image AI\n3. Is this a repetitive process? → Workflow AI\n\n## The Rule of Three\nDon't try to learn 20 tools. Pick 3 that cover your most common use cases and master those first. Breadth comes after depth.`,
    task_steps: [
      { step: 1, instruction: 'List your 5 most common work tasks. For each one, identify which category of AI tool would help most (Text, Image, Video, Productivity, Research).', tip: 'Most office workers find 3–4 of their top 5 tasks are text/language tasks.' },
      { step: 2, instruction: 'Create a free account on ONE tool you haven\'t tried before from this course. Explore it for 10 minutes.', tip: 'Perplexity, Claude, or Notion AI are good starting points if you haven\'t tried them.' },
      { step: 3, instruction: 'Write your personal AI toolkit: 3 tools you will commit to learning. State what task each covers for your specific role.', tip: 'Be specific: not "ChatGPT for writing" but "ChatGPT for writing sponsor recap emails after events."' },
      { step: 4, instruction: 'Share your toolkit with one colleague and ask what tools they use. Note any new ones that seem relevant.', tip: 'Peer learning is the fastest way to discover high-value tools in your specific context.' },
    ],
    questions: [
      { question: 'Which tool category is best for automating a repetitive process like moving data between apps?', options: ['Text AI', 'Image AI', 'Workflow AI', 'Research AI'], correct_index: 2, explanation: 'Workflow AI (Zapier, Make, n8n) specialises in connecting tools and automating multi-step processes. Text AI writes, Workflow AI orchestrates.' },
      { question: 'You need to produce a high-quality visual concept for a new event brand. Which tool category should you use?', options: ['Text AI', 'Image AI', 'Productivity AI', 'Research AI'], correct_index: 1, explanation: 'Image AI (Midjourney, Canva AI, DALL-E) is built for visual creation and editing.' },
      { question: 'What is the "Rule of Three" in this course?', options: ['Use three prompts for every task', 'Master three tools before exploring more', 'Always test three AI tools before picking one', 'Each AI tool works for three types of tasks'], correct_index: 1, explanation: 'Breadth without depth wastes time. Picking 3 tools and mastering them builds real productivity faster than experimenting with 20.' },
      { question: 'Perplexity is best used for:', options: ['Writing long documents', 'Generating images', 'Research with cited, up-to-date sources', 'Automating email workflows'], correct_index: 2, explanation: 'Perplexity searches the web in real time and cites its sources — making it ideal for research tasks where accuracy and currency matter.' },
      { question: 'You want to edit a recorded podcast episode to remove filler words and silences. Which tool fits?', options: ['ChatGPT', 'Midjourney', 'Descript', 'Notion AI'], correct_index: 2, explanation: 'Descript transcribes audio and lets you edit it like a document — including automatic filler word removal.' },
    ],
    estimated_minutes: 20,
  },

  /* ─── FOUNDATION 4 ─────────────────────────────────────────── */
  {
    title: 'Writing with AI: From Blank Page to Final Draft',
    subtitle: 'Use AI to write faster without losing your voice',
    tool_name: 'ChatGPT / Claude',
    tier_level: 'foundation',
    dept_tags: [],
    is_mandatory: true,
    overview: `Writing is the most universal work skill — and the one AI helps most immediately. But most people use AI wrong: they ask for a full draft and either love it uncritically or reject it entirely.\n\nThe right model is AI as a writing partner. You bring the thinking, the context, and the final judgment. AI handles the blank page, the structure, and the speed. This course teaches you to use that partnership effectively for any type of work writing.`,
    read_content: `# Writing with AI: The Right Mental Model\n\nAI is not a ghostwriter. It's a first-draft engine. The difference matters:\n\n- **Ghostwriter:** You hand off the task and accept the output.\n- **First-draft engine:** AI removes the blank page. You shape, refine, and own the result.\n\n## The 4-Step Writing Partnership\n\n**Step 1: Brief AI properly**\nDon't just say "write an email." Give it:\n- Who is the reader and what do they care about?\n- What do you want them to do after reading?\n- What tone? (formal / conversational / urgent / friendly)\n- What details must be included?\n\n**Step 2: Read the draft critically**\nNever send AI output without reading it. Ask:\n- Does this sound like me / our brand?\n- Are the facts correct?\n- Is anything missing or wrong in tone?\n\n**Step 3: Refine by instruction**\nDon't rewrite everything manually — tell AI what to fix:\n> "Make the opening stronger — the current one is too generic."\n> "The third paragraph is too long. Cut it to 2 sentences."\n> "Add a specific call to action at the end."\n\n**Step 4: Final human review**\nRead the final version as the recipient would. This step is always yours.\n\n## Types of Work Writing AI Handles Well\n- **Emails:** Confirmation, follow-up, escalation, intro, recap\n- **Reports:** Status updates, event summaries, post-mortems\n- **Proposals:** First drafts of sponsorship decks, vendor briefs\n- **Social content:** LinkedIn posts, event announcements\n- **Internal comms:** Team updates, meeting recaps, policy summaries\n\n## Tone Control\nTone is the most underused prompt skill. Try these:\n> "Write this more directly — remove all softening language."\n> "Make it warmer. This person is a long-term partner, not a new contact."\n> "This needs to be urgent without sounding panicked."`,
    task_steps: [
      { step: 1, instruction: 'Pick one real email or document you need to write today. Write a one-paragraph brief for AI: who\'s reading it, what you need them to do, what tone, what details.', tip: 'The brief takes 2 minutes and the output quality difference is enormous.' },
      { step: 2, instruction: 'Paste your brief into ChatGPT or Claude and get the first draft. Read it carefully — note 2–3 things that need changing.', tip: "Don't accept or reject it wholesale. Read it like an editor." },
      { step: 3, instruction: 'Send 2 refinement instructions (one at a time) to fix the issues you spotted. Compare the revised version to the original.', tip: 'Good refinement instructions are specific: "The opening is too formal" beats "make it better."' },
      { step: 4, instruction: 'Save your best prompt + the final output as a template for this type of writing. You now have a reusable asset.', tip: 'After 5–10 writing tasks with AI, you\'ll have a personal prompt library for your role.' },
    ],
    questions: [
      { question: 'The correct mental model for AI-assisted writing is:', options: ['AI as ghostwriter — hand off and accept', 'AI as first-draft engine — you shape and own the result', 'AI as spell-checker only', 'AI as a replacement for human judgment in writing'], correct_index: 1, explanation: 'AI removes the blank page and builds the structure. You bring the thinking, the context, and the final call on what gets sent.' },
      { question: 'You receive an AI-drafted email and notice the tone is too stiff for this particular client. What do you do?', options: ['Send it anyway — the content is correct', 'Rewrite the whole thing yourself', 'Tell AI: "This is too formal for this client — make it warmer and more conversational"', 'Use a different AI tool'], correct_index: 2, explanation: 'Specific refinement instructions are faster and more effective than rewriting. AI responds well to precise tone direction.' },
      { question: 'Which of these should you ALWAYS do before sending an AI-drafted document?', options: ['Run it through a grammar checker', 'Read it as the recipient would — checking tone, facts, and missing elements', 'Ask a colleague to review it', 'Run the same prompt again to get a second version'], correct_index: 1, explanation: 'Human review is non-negotiable. AI can produce plausible but incorrect facts, wrong tone, or missing context that only you can catch.' },
      { question: 'What makes a good AI writing brief?', options: ['Just the task — keep it short so AI has room to be creative', 'Reader, desired action, tone, and key details', 'The full history of the project', 'A word count target'], correct_index: 1, explanation: 'A brief that specifies reader, goal, tone, and details gives AI exactly what it needs to produce a usable first draft.' },
      { question: 'After completing 10 AI writing tasks, what should you have built?', options: ['A report for your manager', 'A personal prompt library for your most common writing types', 'A subscription to a paid AI tool', 'Nothing — each task starts fresh'], correct_index: 1, explanation: 'Saving your best prompts as reusable templates turns each AI task into a long-term productivity asset.' },
    ],
    estimated_minutes: 20,
  },

  /* ─── FOUNDATION 5 ─────────────────────────────────────────── */
  {
    title: 'AI for Meetings: Before, During, and After',
    subtitle: 'Cut meeting waste in half using AI at every stage',
    tool_name: 'ChatGPT / Otter.ai / Fireflies',
    tier_level: 'foundation',
    dept_tags: [],
    is_mandatory: false,
    overview: `Meetings consume more time than almost any other work activity — and most of that time is wasted on preparation that didn't happen, notes that aren't taken, and follow-up that never gets done.\n\nAI can be applied at every stage of a meeting to cut that waste significantly. This course gives you a practical system for using AI before, during, and after every meeting.`,
    read_content: `# The AI Meeting System\n\n## Before the Meeting\n\n**Agenda generation:**\n> "I have a 45-minute meeting with our venue partner about the June summit. We need to confirm AV setup, catering finalisation, and parking logistics. Write a structured agenda with time allocations."\n\n**Pre-read summary:**\nPaste any brief, email thread, or document and ask:\n> "Summarise the key context I need before this meeting in 5 bullet points."\n\n**Question preparation:**\n> "Based on this vendor contract, what are the 5 questions I should clarify before signing?"\n\n## During the Meeting\n\n**AI note-taking tools** (record + transcribe automatically):\n- **Otter.ai** — real-time transcription, free tier available\n- **Fireflies.ai** — joins your Zoom/Meet/Teams call, takes notes, creates summaries\n- **Microsoft Copilot** — built into Teams for Microsoft365 users\n\nThese tools give you a full transcript + AI-generated summary with action items — without you lifting a pen.\n\n**Manual method** (no extra tool needed):\nType rough notes as the meeting runs. Immediately after, paste into ChatGPT:\n> "These are my rough notes from a 30-minute meeting. Write a clean recap with: key decisions made, action items (with owners), and open questions."\n\n## After the Meeting\n\n**Recap email:**\n> "Based on these meeting notes, write a professional recap email to send to all attendees. Include decisions made, action items with owners and deadlines, and next meeting date."\n\n**Task extraction:**\n> "From these notes, extract all action items. Format as a table: Task | Owner | Deadline."\n\n**Follow-up drafting:**\n> "Write a follow-up email to [Name] requesting the venue floor plan they promised to share by Friday."\n\n## The 10-Minute Rule\nFor any meeting over 30 minutes: spend 5 minutes before (AI prep) and 5 minutes after (AI recap). This replaces 30+ minutes of manual work and produces better outputs.`,
    task_steps: [
      { step: 1, instruction: 'Pick an upcoming meeting. Use ChatGPT to generate a structured agenda with time allocations. Send it to attendees 24 hours before.', tip: 'Even a simple agenda increases meeting focus dramatically.' },
      { step: 2, instruction: 'During or immediately after your next meeting, paste your rough notes into ChatGPT and ask for a structured recap with decisions, actions, and open questions.', tip: 'Rough notes work fine — even bullet fragments and half-sentences. AI cleans them up.' },
      { step: 3, instruction: 'Create a free Otter.ai or Fireflies.ai account. Use it on one video call this week. Compare its AI summary to what you would have written manually.', tip: 'The time saving is usually 20–40 minutes per meeting.' },
      { step: 4, instruction: 'Use the recap from Step 2 or 3 to write a follow-up email to attendees. Time how long it takes versus your usual method.', tip: 'Most people find this takes under 3 minutes with AI versus 15–20 minutes manually.' },
    ],
    questions: [
      { question: 'Which AI tool joins your video call automatically and produces a transcript + summary without manual notes?', options: ['ChatGPT', 'Fireflies.ai', 'Perplexity', 'Adobe Firefly'], correct_index: 1, explanation: 'Fireflies.ai (and Otter.ai) integrate with Zoom, Meet, and Teams to record, transcribe, and summarise meetings automatically.' },
      { question: 'You have rough, disorganised meeting notes. What is the fastest way to turn them into a usable recap?', options: ['Rewrite them yourself', 'Paste them into ChatGPT with a prompt asking for a structured summary', 'Email attendees asking for their notes', 'Leave them — you\'ll remember the important parts'], correct_index: 1, explanation: 'ChatGPT turns rough notes into a clean recap in under 30 seconds. The quality of the input notes doesn\'t need to be high.' },
      { question: 'The "10-Minute Rule" in this course means:', options: ['Every meeting should be under 10 minutes', 'Spend 5 minutes on AI prep before and 5 minutes on AI recap after meetings over 30 minutes', 'You should summarise 10 meetings before judging AI effectiveness', 'AI meeting tools save 10 minutes per hour'], correct_index: 1, explanation: '5 minutes before + 5 minutes after replaces 30+ minutes of manual preparation and documentation work.' },
      { question: 'What should a good AI-generated meeting recap include?', options: ['A full transcript of everything said', 'Key decisions made, action items with owners, and open questions', 'A list of who attended and for how long', 'The agenda only'], correct_index: 1, explanation: 'Decisions, actions (with owners), and open questions are the three outputs that drive follow-through after a meeting.' },
      { question: 'Before signing a vendor contract, which AI prompt is most useful?', options: ['"Summarise this contract"', '"Is this contract good?"', '"Based on this contract, what are the 5 questions I should clarify before signing?"', '"Rewrite this contract in simpler language"'], correct_index: 2, explanation: 'Specific question extraction is more actionable than a generic summary. It prepares you for the negotiation conversation.' },
    ],
    estimated_minutes: 20,
  },

  /* ─── FOUNDATION 6 ─────────────────────────────────────────── */
  {
    title: 'AI Tools for Your Role',
    subtitle: 'Department-specific AI use cases that save time today',
    tool_name: null,
    tier_level: 'foundation',
    dept_tags: [],
    is_mandatory: false,
    overview: `Generic AI advice only goes so far. What matters is knowing exactly how AI applies to your specific job — the tasks you do daily, the outputs you're responsible for, the pressure points in your workflow.\n\nThis course maps AI use cases to each department at Trescon. Find your department, find your use cases, start there.`,
    read_content: `# AI Use Cases by Department\n\n## Events\n- Venue RFP drafts and vendor briefing documents\n- Run-of-show schedules and logistics checklists\n- Speaker briefing packs and post-event reports\n- Attendee communication sequences (confirmation, reminder, follow-up)\n\n## Sales & Sponsorship\n- Personalised sponsorship proposals (AI drafts, you customise)\n- Objection-handling scripts for common sponsor pushbacks\n- Lead research summaries from LinkedIn and company websites\n- Follow-up email sequences for deal pipeline stages\n\n## Marketing\n- Social media content calendars and post drafts\n- Email campaign copy for event promotion\n- Ad headline and copy variations for A/B testing\n- Event landing page copy optimisation\n\n## Finance\n- Budget narrative summaries for board presentations\n- Vendor payment terms comparison and analysis\n- Invoice follow-up email templates\n- Financial commentary drafts from raw numbers\n\n## HR & Recruitment\n- Job description drafts tailored to role level and location\n- Interview question banks by competency\n- Offer letter and rejection email templates\n- Onboarding checklist generation\n\n## Content & Design\n- Blog post outlines and first drafts\n- Event theme concept development\n- Caption writing for social assets\n- Press release drafts\n\n## Operations\n- SOP (standard operating procedure) documentation from rough notes\n- Vendor comparison matrices\n- Risk assessment frameworks for event logistics\n- Status update reports from raw data\n\n## Government Relations\n- Briefing note drafts for government meetings\n- Proposal frameworks for B2G pitches\n- Protocol and etiquette research summaries\n- Official correspondence templates\n\n## DemandifyMedia\n- Lead nurture email sequences\n- Prospect research and intent signal summaries\n- B2B content for LinkedIn and email outreach\n- Campaign performance narrative summaries\n\n## The Universal Rule\nFor any task in your role: if the output is a document, email, report, or plan — AI can write the first draft in under 2 minutes. Your value is the judgment, the context, and the final call.`,
    task_steps: [
      { step: 1, instruction: 'Find your department in the list above. Pick the one use case that would save you the most time this week.', tip: 'The highest-value use case is usually the one you find most tedious or time-consuming.' },
      { step: 2, instruction: 'Do that task right now using AI. Use the 3-part prompt formula: Role + Task + Context.', tip: 'If the first output isn\'t right, refine it once. Don\'t give up after the first attempt.' },
      { step: 3, instruction: 'Time how long it took with AI versus your usual approach. Calculate the weekly and annual time saving if you did this every time.', tip: '20 minutes saved per day = over 80 hours per year. That\'s 2 full working weeks.' },
      { step: 4, instruction: 'Write down two more use cases from your department you\'ll try next week. Put them in your calendar as reminders.', tip: 'Scheduling the practice is what makes AI adoption stick.' },
    ],
    questions: [
      { question: 'A Sales executive wants to personalise a sponsorship proposal for a new fintech client. Which AI approach is most effective?', options: ['Ask AI to write a generic sponsorship proposal', 'Provide AI with the client\'s industry, company size, event goals, and ask it to write a personalised proposal section', 'Use AI only to fix grammar after writing it manually', 'Ask AI what sponsorship is'], correct_index: 1, explanation: 'Specificity is everything in sales AI. The more context you provide (industry, pain points, goals), the more personalised and persuasive the output.' },
      { question: 'An HR manager needs to write 15 job descriptions for a recruitment drive. How should AI be used?', options: ['Write all 15 from scratch manually to ensure quality', 'Create one AI prompt template with role-level and location variables, then adapt for each role', 'Use AI for junior roles only', 'Copy-paste one description and change the title'], correct_index: 1, explanation: 'A reusable prompt template with variables (role, level, location, team) lets you produce 15 quality job descriptions in a fraction of the time.' },
      { question: 'What is the "Universal Rule" for AI and document tasks?', options: ['Always use AI for final output', 'If the output is a document, email, report, or plan — AI can draft it in under 2 minutes', 'AI works better for some departments than others', 'Use AI only when you\'re stuck'], correct_index: 1, explanation: 'Any language output (document, email, report, plan) is a candidate for AI first-drafting. Your value is the judgment and context you bring.' },
      { question: 'A Government Relations manager needs to prepare briefing notes before a senior ministry meeting. Which AI use case applies?', options: ['Image AI for presentation design', 'Text AI for researching protocol, drafting briefing note structure, and preparing official correspondence templates', 'Workflow AI to automate the meeting schedule', 'No AI use case exists for this role'], correct_index: 1, explanation: 'Briefing notes, protocol research, and formal correspondence are all strong text AI applications for Government Relations.' },
      { question: 'You save 20 minutes per day by using AI for one regular task. How much time is that over a working year?', options: ['About 10 hours', 'About 40 hours', 'About 80 hours', 'About 120 hours'], correct_index: 2, explanation: '20 min/day × 240 working days = 4,800 minutes = 80 hours per year — the equivalent of 2 full working weeks.' },
    ],
    estimated_minutes: 25,
  },

  /* ─── ADOPTION 3 ─────────────────────────────────────────── */
  {
    title: 'Email and Calendar AI: Reclaim 1 Hour Every Day',
    subtitle: 'Systematically cut the time you spend on email and scheduling',
    tool_name: 'ChatGPT / Gmail AI / Outlook Copilot',
    tier_level: 'adoption',
    dept_tags: [],
    is_mandatory: true,
    overview: `Email and calendar management consume 2–3 hours of most professionals' days. AI can cut that by at least half without sacrificing quality — and often improving it.\n\nThis course gives you a systematic approach to using AI for every stage of email: reading, writing, following up, and scheduling. The goal is 1 hour back in your day, every day.`,
    read_content: `# Email and Calendar AI — Full System\n\n## Reading Email Faster\n\n**Summarise long threads:**\nPaste any email chain into ChatGPT:\n> "Summarise this email thread in 3 bullet points: key context, what's being asked of me, and what the deadline is."\n\n**Prioritise your inbox:**\n> "Here are my 12 unread emails (pasted). Tell me which 3 require action today and what that action is."\n\n## Writing Email Faster\n\n**Standard response types to template:**\n- Vendor follow-up\n- Client recap\n- Sponsor pitch reply\n- Internal escalation\n- Decline/not-interested response\n\nFor each type, build one AI prompt template. Then you spend 30 seconds customising instead of 15 minutes writing.\n\n**Tone matching:**\nPaste the email you received and ask:\n> "Write a reply to this email that matches the tone of the sender and addresses each point they raised."\n\n## The 5 High-Value Email Templates\n\n**1. The Soft Chase**\n> "Write a polite follow-up to a contact who hasn't replied in 5 days. Reference our previous conversation about [topic]. Keep it under 4 sentences."\n\n**2. The Hard No (Diplomatically)**\n> "Write a professional decline email that preserves the relationship. We can't accommodate their request for [X] but want to keep the door open."\n\n**3. The Meeting Request**\n> "Write a concise meeting request email to [role/name] at [company] for a 30-minute call to discuss [topic]. Include 3 suggested times."\n\n**4. The Post-Meeting Recap**\n> "Write a post-meeting recap email based on these notes. Include decisions, actions, and next steps."\n\n**5. The Internal Escalation**\n> "Write a clear escalation email to my manager about [issue]. Include what's happened, the impact, and what I need from them."\n\n## Calendar AI\n\n**Scheduling assistants:** Calendly, Cal.com (automated scheduling without the back-and-forth)\n\n**AI for meeting prep:** Always block 5 minutes before any meeting. Use that time to paste the relevant context into ChatGPT and get a 3-bullet prep summary.\n\n**Weekly planning:**\n> "Based on these priorities for the week (paste list), suggest how I should block my calendar to make sure the most important things get done first."`,
    task_steps: [
      { step: 1, instruction: 'Identify the 3 types of emails you write most often at work. For each, write a reusable AI prompt template.', tip: 'The template should have [placeholders] for the details that change each time (name, topic, date).' },
      { step: 2, instruction: 'Pick your most cluttered email thread this week. Paste it into ChatGPT and ask it to extract: what\'s being asked of you and when.', tip: 'Long email chains often hide the actual ask. AI surfaces it in seconds.' },
      { step: 3, instruction: 'Use one of your new templates to write a real email today. Time how long it takes compared to your usual approach.', tip: 'Target: under 3 minutes per email using AI versus 10–15 minutes manually.' },
      { step: 4, instruction: 'Set up Calendly or Cal.com for your most common meeting type (e.g., 30-min call). Send the link instead of email back-and-forth next time.', tip: 'Scheduling automation alone saves most people 30+ minutes per week.' },
    ],
    questions: [
      { question: 'What is the most efficient way to handle a 20-email thread to find what\'s being asked of you?', options: ['Read every email from the beginning', 'Paste the thread into ChatGPT and ask it to extract the ask and deadline', 'Call the sender directly', 'Archive the thread and wait for a follow-up'], correct_index: 1, explanation: 'AI can scan a long thread and extract the core action item in seconds — far faster than reading every email.' },
      { question: 'What makes an email prompt template reusable?', options: ['It\'s very specific to one person', 'It uses [placeholders] for the details that change each time', 'It includes the full email history', 'It\'s written in a formal tone'], correct_index: 1, explanation: 'Placeholders make templates adaptable. You keep the structure and AI logic, and swap in the specific details for each use.' },
      { question: 'The "Soft Chase" template is used for:', options: ['Declining a meeting request', 'Following up with someone who hasn\'t replied in several days', 'Escalating an issue to your manager', 'Sending a post-meeting recap'], correct_index: 1, explanation: 'The Soft Chase is a polite, short follow-up that references the previous conversation without pressure.' },
      { question: 'What does Calendly solve?', options: ['Email writing speed', 'The back-and-forth of finding a mutual meeting time', 'Video call quality', 'Meeting note-taking'], correct_index: 1, explanation: 'Calendly lets people book directly into your calendar based on your availability — eliminating the email exchange of "does Tuesday work for you?"' },
      { question: 'How should you use the 5 minutes before an important meeting?', options: ['Check your other emails', 'Paste the relevant context into ChatGPT and get a 3-bullet prep summary', 'Reread all previous meeting notes', 'Write the meeting agenda'], correct_index: 1, explanation: 'A 5-minute AI prep gets you context, key points, and questions to ask — arriving ready instead of cold.' },
    ],
    estimated_minutes: 25,
  },

  /* ─── ADOPTION 4 ─────────────────────────────────────────── */
  {
    title: 'Data and Reporting with AI',
    subtitle: 'Turn raw numbers into insights and narratives — fast',
    tool_name: 'ChatGPT / Gemini / Excel AI',
    tier_level: 'adoption',
    dept_tags: ['Finance', 'Sales & Sponsorship', 'Marketing', 'Operations', 'DemandifyMedia'],
    is_mandatory: false,
    overview: `Data only becomes useful when it becomes a story. Most professionals spend more time formatting and explaining numbers than actually using them to make decisions.\n\nThis course shows you how to use AI to: interpret data you're given, write the narrative around numbers, spot patterns, and produce reports in a fraction of the usual time.`,
    read_content: `# Data and Reporting AI — Practical Guide\n\n## What AI Can Do with Data\n\nAI doesn't replace Excel or your BI tool. It makes the interpretation and communication of data faster.\n\n**What AI is great at:**\n- Writing the narrative around numbers ("What does this data mean?")\n- Summarising a dataset into key takeaways\n- Suggesting what metrics to include in a report\n- Spotting trends when you describe the data\n- Writing the executive summary of a report\n\n**What AI is NOT good at:**\n- Running calculations on raw data (use Excel/Sheets for this)\n- Accessing your live dashboards (unless you paste the data)\n- Verifying its own maths (always check calculations)\n\n## Technique 1: Narrative from Numbers\n\nPaste your key metrics and ask:\n> "Here are our event registration numbers for Q1: [paste data]. Write a 3-paragraph executive summary for leadership — highlight the top result, the biggest concern, and one recommended action."\n\n## Technique 2: Data Interpretation\n\n> "Our open rate dropped from 28% to 19% over the last 3 campaigns. What are the most likely reasons and what should we test first?"\n\nYou describe the pattern — AI generates hypotheses. You validate with context.\n\n## Technique 3: Report Structure\n\n> "I need to write a post-event report for our Dubai summit. What sections should it include and what data should each section reference?"\n\nAI gives you the shell. You fill it with your actual numbers.\n\n## Technique 4: Presentation Narrative\n\n> "Here are the key stats from our Q2 sponsorship performance: [data]. Write 5 slide titles and a one-sentence narrative for each that tells a coherent story for the board."\n\n## The Sanity Check Rule\nAI-generated number narratives must be verified against the actual source data before they go to leadership or clients. AI can misread what you paste or make confident-sounding errors. Your name is on the report.`,
    task_steps: [
      { step: 1, instruction: 'Take a report or dataset you need to communicate this week. Paste the key metrics into ChatGPT and ask it to write an executive summary paragraph.', tip: 'You\'re testing how well AI reads your numbers. Read the output critically before using it.' },
      { step: 2, instruction: 'Ask AI to suggest what\'s missing from your current report — what metrics or sections would make it more useful to the reader.', tip: '"What would a CFO want to see in this report that isn\'t here?" is a surprisingly powerful prompt.' },
      { step: 3, instruction: 'Take one trend or anomaly in your data (a drop, a spike, an unexpected result) and ask AI for 3–5 hypotheses about why it happened.', tip: 'AI hypotheses are starting points, not conclusions. Use them to direct your investigation.' },
      { step: 4, instruction: 'Write the narrative section of a real report using AI. Compare it to how you would have written it manually. Note what AI got right and what needed fixing.', tip: 'Most people find AI gets structure and flow right, but needs specific numbers and context corrected.' },
    ],
    questions: [
      { question: 'What is AI most useful for in a data reporting context?', options: ['Running complex calculations', 'Writing the narrative and interpretation around numbers', 'Accessing live dashboards', 'Replacing Excel for data analysis'], correct_index: 1, explanation: 'AI excels at turning numbers into stories — writing the executive summary, the trend interpretation, and the recommended action.' },
      { question: 'You notice a spike in event registrations in week 3. What is the most useful AI prompt?', options: ['"Is this spike good or bad?"', '"Calculate the exact percentage increase"', '"Our registrations spiked in week 3. What are the most likely reasons and what should I investigate first?"', '"Write me a report about registrations"'], correct_index: 2, explanation: 'Asking for hypotheses gives you a structured investigation framework. AI generates the options; you apply your context to evaluate them.' },
      { question: 'The Sanity Check Rule requires that:', options: ['All AI outputs are sent to IT for review', 'AI-generated number narratives are verified against source data before going to leadership', 'You run every prompt twice', 'Only finance staff use AI for data tasks'], correct_index: 1, explanation: 'AI can misread pasted data or generate confident-sounding errors. Human verification of any number that will be presented to leadership or clients is non-negotiable.' },
      { question: 'You need to write a post-event report but don\'t know where to start. What is the best first AI prompt?', options: ['"Write my post-event report"', '"What sections should a post-event report include and what data should each cover?"', '"Summarise the event"', '"How many people attended the event?"'], correct_index: 1, explanation: 'Asking for structure before content gives you a framework to fill in. It\'s faster than asking for a full report without knowing what\'s expected.' },
      { question: 'Which task should always be done in Excel or Sheets rather than AI?', options: ['Writing the narrative around results', 'Running calculations on raw data', 'Drafting the executive summary', 'Suggesting what metrics to include'], correct_index: 1, explanation: 'AI is not a reliable calculator. Always use your spreadsheet tool for maths and pass the results to AI for interpretation and narrative.' },
    ],
    estimated_minutes: 25,
  },

  /* ─── ADOPTION 5 ─────────────────────────────────────────── */
  {
    title: 'AI for Presentations and Proposals',
    subtitle: 'Build compelling decks and proposals in half the time',
    tool_name: 'ChatGPT / Gamma / Beautiful.ai',
    tier_level: 'adoption',
    dept_tags: ['Sales & Sponsorship', 'Events', 'Marketing', 'Leadership'],
    is_mandatory: false,
    overview: `Presentations and proposals are high-stakes outputs — they win sponsors, close deals, and represent Trescon at the highest level. They also take enormous time to produce.\n\nAI doesn't design your deck. But it does everything that takes the longest: structuring the narrative, writing the slide content, drafting the executive summary, and generating multiple versions to choose from.`,
    read_content: `# Presentations and Proposals with AI\n\n## The Structure Problem\n\nMost people start presentations by opening PowerPoint. That's the wrong first step. The narrative structure should come before any design.\n\n**Right sequence:**\n1. Define the audience and goal (2 minutes)\n2. Use AI to generate the narrative structure (2 minutes)\n3. Fill in the content (with AI help)\n4. Design (last, and minimal)\n\n## Step 1: Narrative Structure\n\n> "I'm creating a sponsorship proposal for a fintech company sponsoring the World AI Show in Dubai. The audience is the CMO. The goal is to get a $50,000 sponsorship commitment. Give me a 7-slide presentation structure with a title and one-line objective for each slide."\n\n## Step 2: Slide Content\n\nFor each slide:\n> "Write the content for Slide 3 — 'Why This Event' — 3 bullet points, each under 15 words, focused on what a fintech CMO cares about: audience quality, deal opportunities, and brand credibility."\n\n## Step 3: Executive Summary\n\n> "Write a 3-sentence executive summary for this sponsorship proposal. It should communicate what we're offering, why it's valuable for them specifically, and what we're asking for."\n\n## Step 4: Objection Handling\n\n> "What are the 3 most likely objections a CMO would have to this sponsorship package, and how should I address each one?"\n\n## AI Presentation Tools\n\n**Gamma.app** — AI-generated presentations from a prompt or outline. Design included. Exports to PowerPoint.\n\n**Beautiful.ai** — Smart slide templates that auto-format as you add content.\n\n**ChatGPT with Code Interpreter** — Can create basic charts and visual summaries from data you paste.\n\n## The Multiple Versions Technique\n\nFor any proposal section, generate 3 versions:\n> "Write 3 versions of the opening slide headline for this proposal: one data-focused, one outcome-focused, one urgency-focused."\n\nPick the strongest. This takes 30 seconds and eliminates the "blank page" problem.`,
    task_steps: [
      { step: 1, instruction: 'Think of a real presentation or proposal you need to create. Write the audience, goal, and key message in one paragraph. Use this as your AI brief.', tip: 'If you can\'t write the goal in one sentence, the presentation isn\'t ready to build yet.' },
      { step: 2, instruction: 'Use ChatGPT to generate the slide structure (titles + one-line objectives for each slide). Review it critically — adjust any slides that don\'t serve the goal.', tip: 'AI structure is usually 80% right. You\'ll move or remove 1–2 slides. That\'s the value of a starting point.' },
      { step: 3, instruction: 'Write the content for the 3 most important slides using AI. For each, ask for 3 versions and choose the best.', tip: 'The three most important slides are usually: the "why this" slide, the offer/solution slide, and the call to action.' },
      { step: 4, instruction: 'Generate the objection-handling section: ask AI for the top 3 objections your audience would have and draft your responses.', tip: 'This is the section most presenters skip — and where deals are lost.' },
    ],
    questions: [
      { question: 'What is the correct sequence for building a presentation with AI?', options: ['Design first, then content, then narrative', 'Open PowerPoint, add slides, ask AI to fill content', 'Define audience and goal → AI narrative structure → fill content → design last', 'Ask AI to build the whole presentation in one prompt'], correct_index: 2, explanation: 'Narrative structure before content before design is the correct sequence. Starting with design decisions before the story is clear wastes time.' },
      { question: 'What does the "Multiple Versions Technique" involve?', options: ['Creating three different presentations', 'Asking AI for 3 versions of a key section and choosing the strongest', 'Running 3 rounds of feedback with stakeholders', 'Using 3 different AI tools for one presentation'], correct_index: 1, explanation: '3 versions in 30 seconds eliminates the blank page problem. You pick the best option rather than defending the only option.' },
      { question: 'Which AI tool generates a full designed presentation from a prompt or outline?', options: ['ChatGPT', 'Perplexity', 'Gamma.app', 'Otter.ai'], correct_index: 2, explanation: 'Gamma.app produces AI-generated presentations with design included, exportable to PowerPoint. It\'s the fastest path from brief to deck.' },
      { question: 'Why should you generate the objection-handling section for every proposal?', options: ['It\'s required by Trescon policy', 'Most deals are lost to unaddressed objections — preparing responses increases close rates', 'AI is most accurate on this section', 'It makes the proposal longer'], correct_index: 1, explanation: 'Unaddressed objections kill deals. Preparing your responses in advance means you can answer confidently in the room instead of being caught off-guard.' },
      { question: 'For a sponsorship proposal targeting a CMO, which content approach is most effective?', options: ['List every feature of the sponsorship package', 'Focus on what a CMO cares about: audience quality, deal opportunities, and brand credibility', 'Use the same deck for all sponsors regardless of role', 'Include the full event history'], correct_index: 1, explanation: 'Role-specific content (what this person cares about) outperforms generic content. AI makes personalisation fast — use it.' },
    ],
    estimated_minutes: 30,
  },

  /* ─── ADOPTION 6 ─────────────────────────────────────────── */
  {
    title: 'Process Mapping with AI',
    subtitle: 'Document, analyse, and improve your team\'s workflows',
    tool_name: 'ChatGPT / Miro / Notion',
    tier_level: 'adoption',
    dept_tags: ['Operations', 'Events', 'HR & Recruitment', 'IT'],
    is_mandatory: false,
    overview: `Most teams run on undocumented processes that live in one person's head. When that person is absent or leaves, the process breaks. When a new person joins, the onboarding takes weeks.\n\nProcess mapping — documenting exactly how work gets done — is one of the highest-leverage things a team can do. AI cuts the time it takes from days to hours.`,
    read_content: `# Process Mapping with AI\n\n## What is a Process Map?\n\nA process map is a step-by-step document that shows:\n- What triggers the process (the start)\n- What steps happen in sequence\n- Who is responsible for each step\n- What the output is (the end)\n- What can go wrong at each step\n\n## Why AI Changes This\n\nTraditionally, process mapping took workshops, interviews, and days of documentation. AI can generate a draft process map from a rough description in minutes — giving your team a starting point to refine rather than a blank page.\n\n## Technique 1: Process Draft from Description\n\n> "I want to document how our team handles event registration from the moment someone fills out the form to the moment they receive their confirmation. Describe this as a step-by-step process with: step name, who does it, what tool is used, and what the output is. Format as a numbered list."\n\n## Technique 2: Process Gap Analysis\n\nPaste your existing process and ask:\n> "Review this event registration process and identify: steps that are manual but could be automated, steps that have no clear owner, and risks if this process breaks at each step."\n\n## Technique 3: SOP Generation\n\n> "Based on this process map, write a Standard Operating Procedure (SOP) document for a new team member. Include: overview, step-by-step instructions, tools needed, common mistakes to avoid, and what to do if something goes wrong."\n\n## Technique 4: Handover Document\n\n> "Write a handover document for this process that someone new could follow on their first day, with no prior context."\n\n## Process Mapping Tools\n\n**Miro** — Visual process maps and flowcharts, collaborative\n**Notion** — Process documentation with linked databases\n**Lucidchart** — Professional flowchart creation\n\nAI generates the content. These tools give it structure and visibility.\n\n## The Minimum Viable Process\nFor any process your team runs more than once a month: document it. It takes 20 minutes with AI. The first time you need to onboard someone or you're on leave and someone needs to cover — you'll know it was worth it.`,
    task_steps: [
      { step: 1, instruction: 'Choose one recurring process in your team that lives in someone\'s head and isn\'t documented. Describe it roughly in 3–5 sentences.', tip: 'Good candidates: event check-in, vendor confirmation flow, invoice approval, content publication process.' },
      { step: 2, instruction: 'Use your description as an AI prompt to generate a full step-by-step process map. Format: step number, who does it, what tool, what output.', tip: 'Don\'t worry if the first draft is 80% right. You\'re editing, not starting from scratch.' },
      { step: 3, instruction: 'Ask AI to do a gap analysis: what\'s manual that could be automated, what has no clear owner, what breaks if one person is absent.', tip: 'The gap analysis often reveals more value than the initial documentation.' },
      { step: 4, instruction: 'Turn the process map into a one-page SOP document using AI. Save it in a shared folder. Tell one colleague where it is.', tip: 'A process that lives in a shared folder is 10x more valuable than one in a notebook.' },
    ],
    questions: [
      { question: 'What are the four components every process map should include?', options: ['Title, author, date, version number', 'Trigger, steps with owners, tools, and output', 'Budget, timeline, team, and risk', 'Input, throughput, output, and feedback'], correct_index: 1, explanation: 'A complete process map needs: what starts it (trigger), who does what and how (steps with owners and tools), and what the end result is (output).' },
      { question: 'AI changes process mapping by:', options: ['Replacing the need for human review', 'Generating a draft process from a rough description in minutes — giving teams a starting point to refine', 'Automating the process directly', 'Creating visual flowcharts automatically'], correct_index: 1, explanation: 'AI eliminates the blank page. A rough description becomes a structured draft in minutes. Teams then refine it rather than starting from scratch.' },
      { question: 'A Process Gap Analysis done by AI should identify:', options: ['The number of staff involved in the process', 'Manual steps that could be automated, steps with no clear owner, and risks at each stage', 'Which tools are most expensive', 'How long each step takes on average'], correct_index: 1, explanation: 'Gap analysis reveals automation opportunities, ownership gaps, and failure points — the three most actionable insights from process documentation.' },
      { question: 'What is the "Minimum Viable Process" principle?', options: ['Only document processes that involve more than 5 people', 'Document any process your team runs more than once a month — it takes 20 minutes with AI', 'Create a full process map only when someone leaves', 'Process maps are only needed for complex technical systems'], correct_index: 1, explanation: 'If a process runs monthly and isn\'t documented, your team is vulnerable every time the key person is absent or leaves. 20 minutes with AI removes that risk.' },
      { question: 'What is a Standard Operating Procedure (SOP) most useful for?', options: ['Strategy decisions', 'Onboarding new team members so they can follow a process independently from day one', 'Leadership reporting', 'Budget approvals'], correct_index: 1, explanation: 'An SOP converts a process map into actionable instructions for someone with no prior context — the core value of process documentation.' },
    ],
    estimated_minutes: 30,
  },

  /* ─── ADVANCED 2 ─────────────────────────────────────────── */
  {
    title: 'AI Strategy for Your Team',
    subtitle: 'Design and lead an AI adoption plan for your department',
    tool_name: null,
    tier_level: 'advanced',
    dept_tags: [],
    is_mandatory: true,
    overview: `Individual AI skills are one thing. Shifting an entire team's behaviour is another. Advanced-track staff at Trescon are expected to do both — be strong AI practitioners themselves AND elevate the capability of their department.\n\nThis course gives you the framework to design, communicate, and execute a team-level AI strategy. It's the difference between being an AI user and being an AI leader.`,
    read_content: `# Designing a Team AI Strategy\n\n## Why Individual AI Skills Aren't Enough\n\nIf one person on a 10-person team uses AI well and the other 9 don't, the team's output is still fragmented. Emails have different quality. Processes are inconsistent. The AI-capable person becomes a bottleneck.\n\nA team AI strategy solves this by making AI adoption the standard, not the exception.\n\n## The 4-Part Team AI Strategy\n\n### Part 1: Current State Assessment\nBefore you can improve anything, you need to know where you are.\n- What tasks does your team do most frequently?\n- Which of those are language-based (writing, summarising, planning)?\n- What's the current TAIRS distribution in your team?\n- Who are your early adopters? Who is resistant?\n\n### Part 2: The Top 3 Use Cases\nDon't try to change everything at once. Pick 3 high-frequency, high-impact use cases for your team and standardise those first.\n\nGood selection criteria:\n- Happens multiple times per week across the team\n- Currently takes 15+ minutes and produces variable quality\n- Has a clear before/after that you can measure\n\n### Part 3: The Adoption Plan\nFor each use case:\n1. **Demonstrate:** Show the team the before/after in a 15-minute session\n2. **Template:** Provide the prompt template so they don't have to write it themselves\n3. **Practise:** Give them a real task to do with the template in the room\n4. **Measure:** Track time saved and quality over the next 4 weeks\n\n### Part 4: The Weekly Rhythm\nAI adoption requires reinforcement:\n- **Weekly:** Share one new AI win from the team in your team meeting\n- **Monthly:** Review TAIRS scores and course completions\n- **Quarterly:** Run a new use case launch (3 per year minimum)\n\n## The Resistance Playbook\n\n**"I don't trust the output"** → Work through a prompt together until the output is right. Resistance to bad outputs is correct — the fix is better prompting, not abandoning AI.\n\n**"It takes longer to prompt than to just do it"** → This is true for the first 3 uses. After that it inverts. The time investment is learning, not the tool.\n\n**"My work is too complex/creative for AI"** → Start with one specific, low-risk task in their role. One concrete win beats a hundred arguments.\n\n**"I'm worried about my job"** → Address directly: AI doesn't replace judgment, relationships, or strategic thinking. It replaces the administrative burden that prevents those things.`,
    task_steps: [
      { step: 1, instruction: 'Complete a Current State Assessment for your team: list your team\'s top 5 tasks, identify which are language-based, and estimate the TAIRS distribution of your direct reports.', tip: 'You may need to run 1:1 conversations to gather this data. Frame it as understanding how to support them, not evaluating performance.' },
      { step: 2, instruction: 'Select your team\'s Top 3 AI use cases using the selection criteria: high frequency, 15+ minutes currently, measurable before/after. Write a one-paragraph brief for each.', tip: 'If you\'re unsure, look at what tasks generate the most complaints or take the most time in your team standups.' },
      { step: 3, instruction: 'Design a 15-minute "AI Demo" for your top use case. Plan: what you\'ll show, what prompt template you\'ll share, what task they\'ll practise, and how you\'ll measure impact.', tip: 'Keep the demo grounded in their actual work. "Here\'s how we\'ll write sponsor recap emails faster" beats a generic ChatGPT demo.' },
      { step: 4, instruction: 'Write your team AI strategy as a one-page document: current state, top 3 use cases, adoption plan, and how you\'ll measure success over 90 days. Share with your manager.', tip: 'A written strategy signals commitment. It also gives your manager context to support you when you need resources or time.' },
    ],
    questions: [
      { question: 'Why is individual AI skill insufficient on its own for team performance?', options: ['Individual users always make mistakes', 'One AI-capable person in a team creates fragmented output and makes that person a bottleneck', 'AI doesn\'t work well for teams', 'Individual skills require expensive tools'], correct_index: 1, explanation: 'When only one person uses AI well, quality is inconsistent across the team and the AI-capable person often ends up doing extra work. Team adoption creates the leverage.' },
      { question: 'What are the correct selection criteria for the Top 3 team use cases?', options: ['Most complex, most technical, most expensive to do manually', 'High frequency, currently takes 15+ minutes, has a measurable before/after', 'Chosen by IT, approved by finance, signed off by leadership', 'The tasks AI can do completely without human input'], correct_index: 1, explanation: 'High frequency ensures impact at scale. 15+ minutes ensures meaningful time savings. Measurability lets you demonstrate ROI.' },
      { question: 'The correct response to "AI takes longer than just doing it" is:', options: ['Accept that AI isn\'t right for this person', 'Agree — AI is only useful for simple tasks', 'Acknowledge that the first 3 uses are slower — this is the learning investment, not the ongoing reality', 'Show them a faster way to prompt'], correct_index: 2, explanation: 'The learning curve is real and temporary. After 3–5 uses of the same type of task, speed inverts significantly. Framing it as investment beats dismissing the concern.' },
      { question: 'The Weekly Rhythm for AI adoption includes:', options: ['Daily AI tool updates sent to the team', 'Weekly AI win sharing, monthly TAIRS review, quarterly new use case launch', 'Weekly reporting to leadership on tool usage', 'Daily check-ins on each team member\'s AI usage'], correct_index: 1, explanation: 'Consistent reinforcement at the right cadence (weekly/monthly/quarterly) builds habit without creating overhead.' },
      { question: 'A team member says "my work is too creative for AI." The best first response is:', options: ['Agree — creative roles shouldn\'t use AI', 'Show them one specific, low-risk AI use case in their role to produce a concrete win', 'Tell them AI adoption is mandatory', 'Give them this course to complete'], correct_index: 1, explanation: 'One concrete win in their specific context converts sceptics faster than any argument. Start specific and small, not broad and abstract.' },
    ],
    estimated_minutes: 35,
  },

  /* ─── ADVANCED 3 ─────────────────────────────────────────── */
  {
    title: 'Custom Automations: Build Your First AI Workflow',
    subtitle: 'Connect tools, add AI steps, and automate a real business process',
    tool_name: 'n8n / Make / Zapier',
    tier_level: 'advanced',
    dept_tags: [],
    is_mandatory: true,
    overview: `You know how to use AI tools. You've automated simple two-step processes. Now it's time to build something real — a multi-step automation that combines AI generation with tool integration to handle a complete business process end-to-end.\n\nThis course walks you through building a custom automation from scratch: from identifying the right process, to designing the flow, to launching and monitoring it.`,
    read_content: `# Building a Custom AI Automation\n\n## What Makes an Automation "Custom"?\n\nA template automation does one thing someone else designed. A custom automation is designed by you for your specific context — combining tools your team actually uses, in a sequence that matches your real workflow.\n\n## The 5-Step Build Process\n\n### Step 1: Map the Current Manual Process\nBefore building anything, write out exactly what happens now:\n> When [trigger] → [Person A] does [Step 1] using [Tool] → [Person B] does [Step 2] → Output is [X]\n\nThis becomes your automation blueprint.\n\n### Step 2: Identify the AI Step\nIn most business processes, there is one step where content needs to be generated or interpreted. That's where an AI node goes.\n\nExamples:\n- New lead comes in → **AI writes personalised intro email** → Email is sent automatically\n- Meeting transcript arrives → **AI generates action item list** → Tasks are created in Asana\n- New sponsor inquiry → **AI scores and categorises it** → Routed to right sales person\n\n### Step 3: Choose Your Builder\n- **Zapier:** Easiest for simple AI + app connections. Large template library.\n- **Make (Integromat):** More powerful. Better for conditional logic and multi-branch flows.\n- **n8n:** Most flexible. Runs locally or self-hosted. Better for complex or sensitive workflows.\n\n### Step 4: Build and Test\n1. Set up the trigger (new form submission, new email, new row in spreadsheet, etc.)\n2. Add your tool connections (Google Sheets, Gmail, Slack, etc.)\n3. Add the AI step (connect ChatGPT or Gemini via API)\n4. Test with real data — not hypothetical\n5. Check every output before turning it on for real traffic\n\n### Step 5: Monitor and Iterate\nNo automation is perfect on launch. Monitor for:\n- Failed runs (tool disconnections, API limits)\n- AI outputs that need prompt refinement\n- New steps that should be added as the process evolves\n\n## Real Automation Example: Sponsor Inquiry Triage\n\n**Trigger:** New form submission on website\n**Step 1:** Extract company name, contact, inquiry type\n**Step 2 (AI):** Score the inquiry (1–5) based on company size, inquiry type, and relevance to upcoming events. Output: score + recommended response type\n**Step 3:** If score ≥ 4 → Notify sales lead on Slack + create CRM entry. If score < 4 → Send auto-reply + add to nurture sequence\n\nThis automation handles what used to be 15 minutes of manual review for every inquiry — at any hour, instantly.\n\n## The API Connection\nMost AI automation nodes (ChatGPT, Gemini) require an API key. These are:\n- Available from the AI provider (OpenAI, Google AI Studio)\n- Used per-request (small cost, but significant)\n- Added once in your automation tool settings`,
    task_steps: [
      { step: 1, instruction: 'Identify a multi-step process in your work that involves: a trigger, at least 2 manual steps, and a content creation or interpretation step where AI could add value.', tip: 'The best candidates involve something repetitive that starts the same way each time (form submission, new email, scheduled time).' },
      { step: 2, instruction: 'Map the current manual process as: Trigger → Step 1 (who, what tool) → Step 2 → ... → Output. Identify specifically where the AI step belongs.', tip: 'Write it out like a recipe. If it\'s clear enough for a new team member to follow, it\'s clear enough to automate.' },
      { step: 3, instruction: 'Build the first version of your automation in Make or n8n. Connect at least 2 tools + 1 AI step. Test with real data before activating.', tip: 'Start with a "dry run" mode where outputs go to a test channel or document rather than live systems.' },
      { step: 4, instruction: 'Run the automation live for one week. Document: how many times it ran, what it produced, what needed manual correction, and what you\'d change.', tip: 'A one-week run gives you real performance data to present as a business case for expanding it.' },
    ],
    questions: [
      { question: 'What is the key difference between a template automation and a custom automation?', options: ['Template automations cost more', 'Custom automations are designed for your specific context, tools, and workflow — not a pre-built generic flow', 'Template automations use AI; custom ones don\'t', 'Custom automations require coding knowledge'], correct_index: 1, explanation: 'A template does what someone else designed. A custom automation is built to match your actual workflow, tools, and specific use case.' },
      { question: 'In the 5-step build process, what comes BEFORE choosing which tool to use?', options: ['Setting up API keys', 'Mapping the current manual process and identifying where the AI step belongs', 'Testing with real data', 'Getting IT approval'], correct_index: 1, explanation: 'The blueprint (current process map + AI step identification) must come before tool selection. Choosing the tool first leads to over-engineered or mismatched automations.' },
      { question: 'In the Sponsor Inquiry Triage example, what does the AI step do?', options: ['Sends the reply email', 'Scores the inquiry and recommends response type based on company size, inquiry type, and event relevance', 'Creates the CRM entry', 'Fills in the form on behalf of the sponsor'], correct_index: 1, explanation: 'The AI step is the intelligence layer — it interprets the inquiry and makes a routing decision so the rest of the automation knows what to do next.' },
      { question: 'After launching a custom automation, you should monitor for:', options: ['Staff reactions to the change', 'Failed runs, AI outputs needing refinement, and new steps to add as the process evolves', 'Cost per run only', 'Whether IT has approved the tool'], correct_index: 1, explanation: 'Monitoring is how you improve. Failed runs need fixing, AI prompts often need tuning after real-world use, and processes evolve — so automations should too.' },
      { question: 'Which automation tool is most recommended for complex, multi-branch flows where you need conditional logic?', options: ['Zapier', 'Make (Integromat)', 'Otter.ai', 'Notion'], correct_index: 1, explanation: 'Make (formerly Integromat) has a more powerful visual builder suited for conditional logic, multiple branches, and complex data transformations.' },
    ],
    estimated_minutes: 40,
  },
]

export async function POST(req: NextRequest) {
  const { admin_code } = await req.json().catch(() => ({}))
  if (admin_code !== ADMIN_CODE) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const rows = ADDITIONAL_COURSES.map(c => ({ ...c, source: 'manual', status: 'published' }))

  const { data, error } = await supabaseAdmin
    .from('courses')
    .insert(rows)
    .select('id, title, tier_level')

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({
    success: true,
    inserted: data?.length ?? 0,
    courses: data?.map(c => ({ id: c.id, title: c.title, tier: c.tier_level })),
  })
}
